<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.1.3" />
        
        <Reference Include="CassieLauncher.SDK">
            <HintPath>..\..\lib\CassieLauncher.SDK.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

</Project>